name: E2E TEST
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests_e2e:
    timeout-minutes: 20
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install browsers
        run: npx playwright install chromium

      - name: Run e2e tests
        run: npm run env:test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Send test results to MS Teams
        env:
          MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
        run: |
          message=$(cat playwright-report/custom-summary.txt)
          content=$(echo "$message" | awk 'BEGIN{ RS=","; ORS="\n" } 1')

          payload='{
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "type": "AdaptiveCard",
            "version": "1.3",
            "body": [
              {
                "type": "TextBlock",
                "text": "Test Results Summery - ",
                "weight": "Bolder",
                "size": "Large"
              },
              {
                "type": "FactSet",
                "facts": [
                  {
                    "title": "Message",
                    "value": "'"$content"'"
                  }
                ]
              }
            ],
            "color": "00FF00",
            "actions": []
          }'

          curl -X POST -H "Content-Type: application/json" -d "$payload" "$MS_TEAMS_WEBHOOK_URL"
