name: E2E TEST
on:
    push:
      branches-ignore:
        - main
    pull_request:
      branches:
        - main
      

jobs:
  tests_e2e:
    timeout-minutes: 20
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install browsers
        run: npx playwright install chromium
      - name: Run e2e tests
        run: npm run env:test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: test-result/
          retention-days: 30
