name: E2E TEST
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests_e2e:
    timeout-minutes: 20
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install browsers
        run: npx playwright install chromium

      - name: Run e2e tests
        run: npm run env:test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Send test results to MS Teams
        env:
          MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
        run: |
          content=$(cat playwright-report/custom-summary.txt)
          IFS=$'\n' read -ra lines <<< "$content"

          card='{
            "type": "MessageCard",
            "themeColor": "0078D7",
            "title": "Test Results",
            "sections": [
              {
                "facts": ['

          for line in "${lines[@]}"; do
            IFS=':' read -r label value <<< "$line"
            label="${label//[$'\t\r\n ']/}"
            value="${value//[$'\t\r\n ']/}"
            card+="{
                  \"name\": \"$label\",
                  \"value\": \"$value\"
                },"
          done

          card="${card%,}]"
          card+='
              ]
            }
          }'

          curl -H "Content-Type: application/json" -d "$card" $MS_TEAMS_WEBHOOK_URL
